export interface AuthorizationData {
    "AUTH_ID":number,
    "READ":string,
    "APP_ID":number,
    "EXECUTE":string,
    "DELETE":string,
    "CREATE":string,
    "ROLE_ID":string,
    "AUTH_CD":string,
    "AUTH_DSC":string,
    "UPDATE":string,
    "id":number,
    "AUTH_FLD":number,
    "is_selected": boolean,
    "is_selected_role": boolean,
}